import { createServer } from 'node:http';
import { createReadStream,existsSync,statSync } from 'node:fs';
import { dirname,extname,join,normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes } from 'node:crypto';
import { openDatabase,verifyPassword } from './database.js';
const root=dirname(fileURLToPath(import.meta.url)),pub=join(root,'public'),db=openDatabase(process.env.DB_PATH||join(root,'data','plc-status.db')),port=Number(process.env.PORT||3000),sessions=new Map();
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml'};
function json(res,code,body,headers={}){res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers});res.end(JSON.stringify(body))}
async function body(req){let b='';for await(const c of req){b+=c;if(b.length>2e6)throw Object.assign(new Error('Za duże żądanie'),{statusCode:413})}try{return b?JSON.parse(b):{}}catch{throw Object.assign(new Error('Nieprawidłowy JSON'),{statusCode:400})}}
function cookie(req){return Object.fromEntries((req.headers.cookie||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2))}
function sessionCookie(req,value,maxAge){const https=req.socket.encrypted||String(req.headers['x-forwarded-proto']||'').split(',')[0].trim()==='https';return `plc_session=${value}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${maxAge}${https?'; Secure':''}`}
function user(req){const s=sessions.get(cookie(req).plc_session);if(!s||s.expires<Date.now()){if(s)sessions.delete(cookie(req).plc_session);return null}return db.me(s.userId)}
const can=(u,role)=>role==='user'?!!u:role==='moderator'?['admin','moderator'].includes(u?.role):u?.role==='admin';
function need(u,role='user'){if(!can(u,role))throw Object.assign(new Error(u?'Brak uprawnień':'Zaloguj się'),{statusCode:u?403:401})}
const id=(path,prefix)=>{const m=path.match(new RegExp(`^${prefix}/(\\d+)$`));return m?Number(m[1]):null};
async function api(req,res,url){const method=req.method||'GET',p=url.pathname,u=user(req),controller=url.searchParams.get('controller')||'all';
 if(method==='GET'&&p==='/api/health')return json(res,200,{status:'ok'});
 if(method==='POST'&&p==='/api/login'){const x=await body(req),found=db.authenticate(x.username);if(!found||!verifyPassword(x.password||'',found.password_hash))return json(res,401,{error:'Nieprawidłowy login lub hasło'});const token=randomBytes(32).toString('hex');sessions.set(token,{userId:found.id,expires:Date.now()+12*3600e3});return json(res,200,db.me(found.id),{'Set-Cookie':sessionCookie(req,token,43200)})}
 if(method==='POST'&&p==='/api/logout'){const t=cookie(req).plc_session;sessions.delete(t);return json(res,200,{ok:true},{'Set-Cookie':sessionCookie(req,'',0)})}
 need(u); if(method==='GET'&&p==='/api/me')return json(res,200,u);if(method==='GET'&&p==='/api/controllers')return json(res,200,db.controllers());if(method==='GET'&&p==='/api/config')return json(res,200,db.config());if(method==='GET'&&p==='/api/dashboard')return json(res,200,db.dashboard(controller));if(method==='GET'&&p==='/api/users')return json(res,200,db.users());
 const resources=[['/api/status',()=>db.status(controller),(i,x)=>db.saveStatus(i,x,u),i=>db.deleteStatus(i)],['/api/tasks',()=>db.tasks(controller),(i,x)=>db.saveTask(i,x,u),i=>db.deleteTask(i)],['/api/open-points',()=>db.points(controller),(i,x)=>db.savePoint(i,x,u),i=>db.deletePoint(i)],['/api/daily-notes',()=>db.notes(controller,url.searchParams.get('from'),url.searchParams.get('to')),(i,x)=>db.saveNote(i,x,u),i=>db.deleteNote(i)],['/api/goals',()=>db.goals(controller),(i,x)=>db.saveGoal(i,x,u),i=>db.deleteGoal(i)]];
 for(const [path,list,save,remove] of resources){if(p===path){if(method==='GET')return json(res,200,list());if(method==='POST')return json(res,201,save(null,await body(req)))}const n=id(p,path);if(n!==null){if(method==='PATCH')return json(res,200,save(n,await body(req)));if(method==='DELETE'){need(u,'admin');remove(n);res.writeHead(204);return res.end()}}}
 if(p==='/api/users'){need(u,'admin');if(method==='POST')return json(res,201,db.saveUser(null,await body(req)))}let n=id(p,'/api/users');if(n!==null){need(u,'admin');if(method==='PATCH')return json(res,200,db.saveUser(n,await body(req)));if(method==='DELETE'){if(n===u.id)throw Object.assign(new Error('Nie możesz usunąć własnego konta'),{statusCode:400});db.removeUser(n);res.writeHead(204);return res.end()}}
 if(p==='/api/controllers'){need(u,'admin');if(method==='POST')return json(res,201,db.saveController(null,await body(req)))}n=id(p,'/api/controllers');if(n!==null){need(u,'admin');if(method==='PATCH')return json(res,200,db.saveController(n,await body(req)));if(method==='DELETE'){db.removeController(n);res.writeHead(204);return res.end()}}
 const cfg=[['/api/categories','category',db.saveCategory],['/api/subcategories','subcategory',db.saveSubcategory],['/api/options','option',db.saveOption]];for(const [path,type,save] of cfg){if(p===path&&method==='POST'){need(u,'moderator');return json(res,201,save(null,await body(req)))}n=id(p,path);if(n!==null){need(u,'moderator');if(method==='PATCH')return json(res,200,save(n,await body(req)));if(method==='DELETE'){need(u,'admin');db.deleteConfig(type,n);res.writeHead(204);return res.end()}}}
 if(method==='PATCH'&&p.startsWith('/api/settings/')){need(u,'admin');const x=await body(req);db.saveSetting(decodeURIComponent(p.slice(14)),x.value);return json(res,200,{ok:true})}
 return json(res,404,{error:'Nie znaleziono endpointu'})
}
function staticFile(res,path){const requested=path==='/'?'/index.html':path,n=normalize(requested).replace(/^(\.\.[/\\])+/,'');const f=join(pub,n);if(!f.startsWith(pub)||!existsSync(f)||!statSync(f).isFile())return json(res,404,{error:'Nie znaleziono pliku'});res.writeHead(200,{'Content-Type':mime[extname(f)]||'application/octet-stream','Cache-Control':extname(f)==='.html'?'no-cache':'public,max-age=3600','Content-Security-Policy':"default-src 'self'; style-src 'self'; script-src 'self'; img-src 'self' data:; connect-src 'self'; base-uri 'self'; form-action 'self'"});createReadStream(f).pipe(res)}
export const server=createServer(async(req,res)=>{try{const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(url.pathname.startsWith('/api/'))return await api(req,res,url);const publicLoginFiles=['/login.html','/login.js','/styles.css'];if(!user(req)&&!publicLoginFiles.includes(url.pathname))return staticFile(res,'/login.html');return staticFile(res,url.pathname)}catch(e){console.error(e);json(res,Number(e.statusCode)||500,{error:Number(e.statusCode)?e.message:'Nieoczekiwany błąd serwera'})}});
if(process.argv[1]===fileURLToPath(import.meta.url))server.listen(port,'0.0.0.0',()=>console.log(`PLC Hub on ${port}`));
function shutdown(){server.close(()=>{db.close();process.exit(0)})}process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
